names
1. "Agent of Reagents"
2. "Alabaster to Zinc"
3. "Alchemical"
4. "Alembics Aplenty"
5. "Aristotle's Alchemy"
6. "Bismuth and Hartshorn"
7. "Bottles of Antimony and More!"
8. "Cauldron Concoctions"
9. "Components and Froths"
10. "Daily Elixirs and Philters"
11. "Draughty Drams"
12. "Inlaid Carafe"
13. "Mercury of Life"
14. "Minerals and Mixtures"
15. "Philosopher's Stone"
16. "Potent Potables"
17. "Rare Earths and Spirits"
18. "Theo's Thaumaturgy"
19. "Uerth's Elements and Elixirs"
20. "Vitriolus Regulus"