names
1. "Alloy Armor"
2. "Almighty Armors"
3. "Ardon's Armory"
4. "Armor & Shield"
5. "Armored Knight"
6. "Chain, Band, and Plate"
7. "He Who Smelt it"
8. "Heavy Metal"
9. "Hides and Helmets"
10. "Invincible Armors"
11. "Ironbrand Armor"
12. "Knight's Defense"
13. "Magnificent Armors"
14. "Mail for the Ages"
15. "Mail to Order"
16. "Mighty Mail"
17. "Positively Plate"
18. "Scales and Mails"
19. "Steel Coats"
20. "The Chain Company"