names
1. "Barks, Berries and Balms"
2. "Barryl's Botanicals"
3. "Bee's Bounty"
4. "Dragon Herbarium"
5. "Earthy Edibles"
6. "Garden Thyme Herbal"
7. "Green Zest Herbal"
8. "Greens and Fungi"
9. "Grotto and Grove"
10. "Healing Thyme"
11. "Herb's Herbs"
12. "Herbs and Spice"
13. "Holly's & Herb's"
14. "Kelp, Seeds and Weeds (near ocean)"
15. "Nature's Gift"
16. "Paul's Plants and Herbs"
17. "Roots, Leaves and Seeds"
18. "Spice of the Earth"
19. "The Garden Market"
20. "The Natural Path"