names
1. "A Foot Above"
2. "Best Foot Forward"
3. "Boot Haul"
4. "Feet Front"
5. "Foot Craft"
6. "Foot's Friend"
7. "Good for the Sole"
8. "Happy Cobbler"
9. "Heel to Toe"
10. "Mended Heel"
11. "Nicely Cobbled"
12. "Perfectly Shod"
13. "Shod for Work"
14. "Sole Oh!"
15. "Sole Savior"
16. "Something Afoot"
17. "Step Smart"
18. "The Cobblery"
19. "Toe, Arch and Heel"
20. "Vamp and Shank"