names
1. "All the Trimmings"
2. "Bazaar of the Green Hippogriff"
3. "Beautiful Bobbles"
4. "Bric-a-brac and Bees Wax"
5. "Dragon Tooth Shop"
6. "Far-flung Favors"
7. "Gallery of Gizmos"
8. "Gilded Emporium"
9. "Grace's Gimcracks"
10. "House of Curiosities"
11. "Lucky Charms"
12. "Niah's Knickknacks"
13. "Novelty Whatnots"
14. "Rare Trinkets Mercantile"
15. "Rose Incense and Ornaments"
16. "Silver Leaf Antiques"
17. "Steel Raven Finery"
18. "Trifles and Talons"
19. "Trinkets & Lore (sage owned)"
20. "Winged Whim-whams"