names
1. "Anouke's Arrow (substitute deity of hunting or war)"
2. "At Long Range"
3. "Bolt Ahead"
4. "Dauntless Arrows"
5. "Exact Archery"
6. "Gilded Bow"
7. "In Firing Range"
8. "Knock and Loose"
9. "Leonard's Miscellaneous Missiles"
10. "Let Loose"
11. "Marksman's Choice"
12. "On the Mark"
13. "Quiver and Quarrel"
14. "Ready Aim Fire"
15. "Right Flight"
16. "Superior Firepower"
17. "The Drawn String"
18. "The Green Arrow"
19. "True Shot"
20. "Vanarien's Archery"