names
1. "Bray's Leather and Whips"
2. "Frontier Leatherworks"
3. "Heide's Tannery"
4. "Hide Handler"
5. "Hidebound Crafts"
6. "Huntsman's Hides"
7. "Leather You Will"
8. "LeatherCraft"
9. "Leathering Heights"
10. "Mountain Man Leatherworks"
11. "Mystic Leather"
12. "Pelthouse"
13. "Rawhide Wright"
14. "Second Skin"
15. "Stormy Leather"
16. "Tanner's Alley"
17. "The Hide You Seek"
18. "The Tanned Hyde"
19. "The Tanning Solution"
20. "Tip Top Tanning"