names
1. "Abjuring Arcanum"
2. "Arcana Eccentrics"
3. "Basilisk Bazaar"
4. "Brooms and Braziers"
5. "Circe's Wonders (substitute deity of magic)"
6. "Copper Chimera"
7. "Dragon's Dowry"
8. "Dweomers and Magic Doobries"
9. "Eldritch Charms"
10. "Evoker's Tools and Treasures"
11. "Ezmerelda's Enchantments"
12. "Invocators Menagerie"
13. "Laughing Phoenix"
14. "Magus Emporium"
15. "Mandall's Magigorium"
16. "Sorcery Source"
17. "Spheres, Scrolls, and Tomes"
18. "The Magic Circle"
19. "The Mystic Mephit"
20. "Wizarding Elements"
21. "Splendorporium"