names
1. "Adventurer's Emporium"
2. "Camp and Trek"
3. "Dark Hawk Mountain Market 4. Delving Kits and Equipment 5. Excursion Shoppe"
6. "Expeditions Unlimited"
7. "Explorer's Edge"
8. "Journeyer Trading Post"
9. "Latitude Longitude Square"
10. "Martinua's General Store"
11. "Meridian and Compass Outlet 12. Minotaur's Horn Supplies"
13. "Missionary's Mart"
14. "Odyssey Outfitters"
15. "Peregrinator Paraphernalia 16. Pioneers' Mercantile"
17. "Tools and Sundry"
18. "Trackless Path Fittings"
19. "Traveler's Trove"
20. "Wildwood Gear"