names
1. "Answers Emporium"
2. "Archivist of the Ages"
3. "Astute Adviser"
4. "Behind the Veil"
5. "Breadth of Academia"
6. "Chronical Keeper"
7. "Cure for Curiosity"
8. "Erudite Elder"
9. "Knowledge is Power"
10. "Learned Centuries"
11. "Learning and Lore"
12. "Master of Mysteries"
13. "Master of the Past"
14. "Redoubt of Research"
15. "Scholar of the Ancients"
16. "The Studious Scriptorium"
17. "The Wondering Eye"
18. "When in Doubt"
19. "Wise Words"
20. "Woman of Letters"