names
1. "Beartooth Ranch"
2. "Colt's Run"
3. "Courser Acres"
4. "Damon's Dapples"
5. "Equus"
6. "EZ Roads Stable"
7. "Fjord Farms"
8. "Foal's Errand"
9. "Knight Ranch"
10. "Lost Creek Ranch"
11. "Mare Junction"
12. "Melody Trails"
13. "Mustang Market"
14. "Posting Paddock"
15. "Saddleback Shires"
16. "Silver Piece Acres"
17. "Sturdy Steeds"
18. "Sunshine Prairies"
19. "The Spirited Equine"
20. "Thoroughbred Riding"