names
1. "Blessed Tailoring"
2. "Cut, Measure & Tack"
3. "Dart, Cord and Bolt"
4. "Fit & Style Clothier"
5. "Fits of Art"
6. "Keeping Y ou in Stitches"
7. "Pins and Needles"
8. "Questing Quilters"
9. "Seam Saver"
10. "Seamless Seamstress"
11. "Stitch in Time"
12. "Stitch Witchery"
13. "Suited to You"
14. "Superior Stitches"
15. "Sylvan Sisters Sewing"
16. "Tailoryd Stytch"
17. "The Gilded Stitch"
18. "The Perfect Fit"
19. "Threading the Needle"
20. "Urbane Clothier"