atmosphere
1. "Brothel/den of ill-repute"
2. "Curious local crowd"
3. "Elder crowd"
4. "Family friendly"
5. "Gambling (public or secret) "
6. "Gathering place for guards "
7. "Insular regulars"
8. "Loud and rough"
9. "Loud, but friendly"
10. "Lively with shows and performances"
11. "Mainly literati, discussing philosophy, poetry and thought"
12. "Multicultural melting pot"
13. "Political den"
14. "Popular with a particular race"
15. "Quiet dive"
16. "Sailors' port of call"
17. "Seedy and dangerous"
18. "Smuggler's den"
19. "Upper-class clientele"
20. "Waystation, stable and inn"

names
1. "After Dark"
2. "Amber Leaf Inn"
3. "Anchor Inn"
4. "Bandy Princess"
5. "Barrels of Beer Pub"
6. "Belching Dragon"
7. "Black Eagle"
8. "Black Rose Pub"
9. "Blackstone's Keep"
10. "Blazing Fires Inn"
11. "Blue Turtle Inn"
12. "Blushing Mermaid"
13. "Bonny Hill"
14. "Boot Hall Tavern"
15. "Brown Bear Inn"
16. "Buccaneer's Haven"
17. "Cackling Hag"
18. "Captain's Quarters"
19. "Cast Iron Kettle"
20. "Castaways"
21. "Circled Star"
22. "Circling Vulture"
23. "Cliffside Haven"
24. "Cobblestone Inn"
25. "Deva's Rest"
26. "Dew Drop Inn"
27. "Dragon's Breath Inn"
28. "Dragon's Lair"
29. "Drinking Centaur"
30. "Drunken Werewolf"
31. "Duck and Goose"
32. "Eagle House"
33. "Fallen Angel"
34. "Field Day Tavern"
35. "Fiery Hearth"
36. "Fire Giant's Demise"
37. "Fireside Inn"
38. "Flaming Troll Pub"
39. "Gentle Moon Inn"
40. "Golden Lamprey"
41. "Gray Mare"
42. "Grimsy's Ale House"
43. "Hall of Feasts"
44. "Hidden Hollow Inn"
45. "Hilltop Manor Inn"
46. "Iron Gate"
47. "Ivory Horn"
48. "Knight House"
49. "Lake of Wine"
50. "Last Flagon"
51. "Last One Standing"
52. "Leaning Post Inn"
53. "Medusa's Head"
54. "Motley Harpy"
55. "Murdered Minotaur"
56. "Net of Stars"
57. "North Shore Inn"
58. "Oceanside Pub"
59. "Olde Flame Tavern"
60. "Perching Falcon"
61. "Pier #2"
62. "Pig and Poke"
63. "Plank and Anchor"
64. "Prancing Unicorn"
65. "Raging Manticore Saloon"
66. "Red Forest Manor"
67. "Roaring Hearth Inn"
68. "Rowdy Beholder"
69. "Royal Pheasant Inn"
70. "Saddle and Sword"
71. "Scotch Dragon"
72. "Sea of Ale"
73. "Sea Shellter"
74. "Shoreside Pub"
75. "Silver Nugget Inn"
76. "Soaring Griffon"
77. "Solo's Place"
78. "Spotted Beast"
79. "Stagger Inn"
80. "Sweetwater Cove"
81. "Tall Mug Inn"
82. "Tankard and Pint"
83. "The Bent Blade"
84. "The Blade and Stars Inn"
85. "The Blue Lanthorn"
86. "The Ogre's Breath Inn"
87. "The Troll's Demise"
88. "Thrush's Nest"
89. "Travelers' Cloak"
90. "Twinkling Star"
91. "Valleyview Inn"
92. "Wandering Wraith"
93. "Waning Moon"
94. "Warrior's Grog"
95. "Weary Knight Inn"
96. "White Dove Inn"
97. "White Hart Inn"
98. "Wine Cellar"
99. "Witches Brew"
100. "Worn Sword"

services
1. "Appraising"
2. "Assassinations"
3. "Bardic (epic, ballad, song, sonnet, poem)"
4. "Baths/steam room"
5. "Carriage travel"
6. "Cartography"
7. "Contracts"
8. "Courier"
9. "Courtesan"
10. "Deciphering/translations"
11. "Dueling/gladiatorial combat (non-lethal or lethal)"
12. "Entertainment (dancing, gambling, games)"
13. "Forgery"
14. "Guide (hunting, prospecting, travel)"
15. "Healing"
16. "Hot spring"
17. "Job board"
18. "Labor (untrained/trained/specialized)"
19. "Laundry"
20. "Letter writing"
21. "Location tours (with local and historical knowledge)"
22. "Massage"
23. "Message running"
24. "Money lending/exchange"
25. "Money laundering"
26. "Painter (portraits, items)"
27. "Postings for work"
28. "Private dining"
29. "Private entrance"
30. "Repairs (armor, weapon, clothing, equipment)"
31. "Safe storage of items"
32. "Shopper/procurement"
33. "Smuggling"
34. "Soothsaying"
35. "Stable (shoeing, tack and saddle repair)"
36. "Strongbox rental"
37. "Tailoring"
38. "Training (combat, specific skills) • Valet/butler/maid"
39. "Veterinary"