names
1. "Armaments Great and Small"
2. "Arms and Dangerous"
3. "Art of the Sword"
4. "Axe, Hammer & Sword"
5. "Battle Ready"
6. "Bear Arms"
7. "Blades of Destiny"
8. "Brilliant Arms"
9. "Cold Steel Smithy"
10. "Crafted Arms"
11. "Kelvan's Smithy"
12. "Nigel's Fine Weapons of War"
13. "Resilient Weapons"
14. "Samson's Swords"
15. "The Ground Axe"
16. "Valiant Arms and Weapons"
17. "Valley Forge"
18. "Weapons and Arms of Power"
19. "Wesley's Weapons"
20. "Wielder's Forge"