symbols
1. "Black Basilisk on a Grey Field"
2. "Black Dragon displayed on a Tan Field"
3. "Blue Serpent on surrounded by Stars on a White Field"
4. "Blue Three-headed Dog above a horizontal Black Battle Ax on a White Field"
5. "Blue Warhammer on a Yellow Field"
6. "Brown Kraken on a Golden Field"
7. "Copper Dragon on a Green Field"
8. "Crimson Whale on Blue-Green Field"
9. "Gold Gauntlet and Lance on a Blue Field"
10. "Golden Eagle with Red Crown above it"
11. "Green Hydra on Red Field"
12. "Grey “Devil” Face with Horns on a Black Field"
13. "Grey Plate Fist on a Dark Blue Field"
14. "Mirrored White Foxes on a Purple Field"
15. "Orange Tiger with Sword on Dark Grey Field"
16. "Purple Stag on Grey Field above two crossed Black Spears"
17. "Rampant Green Griffin surrounded by Yellow Stars on Black Field"
18. "Red Hawk above a bundle of Black Arrows on a White Field"
19. "Red Wolf on White Moon"
20. "Silver Crown and Scepter on a Violet Field"
21. "Silver Shield with Black Hippogriff on Red Field"
22. "Three Black Horses on a Silver Field"
23. "Three horizontal Grey Swords on Green Field"
24. "Two Black crossed Spears with four Moons on a Silver Field"
25. "Two Light Grey Wyverns on a Royal Blue Field"
26. "Two Rampant Silver Unicorns on a Black Field"
27. "Two Red Crossed Battle Axes above a Grey Wolf on a Black Field"
28. "Two White Skeletons crossing Swords on a Dark Grey Field"
29. "Vertical Gold Crossbow flanked by two bundles of Gold Bolts on Blue Field"
30. "Yellow Lightning diagonally placed over crossed Black Swords on Red Filed"